name: code_editor
description: A code editor (dart, js, html,...) for Flutter with syntax highlighting and custom theme.
version: 2.0.1
homepage: https://github.com/CodoPixel/code_editor

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_highlight: ^0.7.0
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
