name: code_editor
description: A code editor (dart, js, html,...) for Flutter with syntax highlighting and custom theme.
version: 2.0.0
homepage: https://github.com/CodoPixel/code_editor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_highlight: ^0.7.0
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

